name: CICD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v2
      - name: Use Node-14
      - uses: actions/setup-node@v1
      with:
        node-version: 14
      - name: Install Dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
      